### ISSUE TITLE
Rename and mutate variables

### ISSUE THREAD

**Issue by paul-buerkner** [jgabry/posterior#12]
For users it might be convenient to have `rename` and `mutate` functionality to make changes to variables similar to how we do it with the related dplyr functions. To avoid function masking, we may want to name them `rename_variables` and `mutate_variables` which would also be consistent with our naming conventions. 

If we decide to implement such functions, we need to think of a proper backend for non-standard evaluation. We could of course use the one of tidyverse but I am not sure how much additional dependencies this implies. @mjskay you may have more experience with this than I have.

**Comment by paul-buerkner** [comment]
Just a quick note that I am working on `mutate_variables` now.

**Comment by paul-buerkner** [comment]
`mutate_variables´ is now supported as well.

```R
x <- as_draws_df(example_draws())
x <- subset(x, variable = c("mu", "tau"))

mutate_variables(x, tau2 = tau^2)
mutate_variables(x, scale = 1.96 * tau, lower = mu - scale)
```

**Comment by jgabry** [comment]
Cool! One small thing from testthat:

```
test-mutate_variables.R:13: warning: mutate_variables works correctly for draws_df objects
Using `as.character()` on a quosure is deprecated as of rlang 0.3.0.
Please use `as_label()` or `as_name()` instead.
```

**Comment by paul-buerkner** [comment]
Thanks. Should be fixed now.

**Comment by ASKurz** [comment]
When adding a new variable to `as_draws_df()` output, is there any advantage to using `mutate_variables()` versus `mutate()`?
