### ISSUE TITLE
Choose license

### ISSUE THREAD

**Issue by paul-buerkner** [jgabry/posterior#20]
I don't have a strong opinion about it but it may be sensible to not use GPL3 as this causes a lot of trouble in industry (not necessarily for good reasons but still). GPL2 seems fine as does more permissive licenses as used by most tidyverse packages for instance.

**Comment by jgabry** [comment]
@mjskay Is Michigan like Columbia in that they have copyright over your code/IP? (All Columbia employees have to sign something like that.) if so we can add Michigan to the copyright holders too.

**Comment by mjskay** [comment]
Good question. I just sent an email to our copyright office to double-check what that should be (if anything).

**Comment by jgabry** [comment]
Thanks!

**Comment by paul-buerkner** [comment]
With the license now chosen and the repo public, I think we can safely close this issue. If it turns out, we need to add more copyright holders, we can just do it or open a new dedicated issue for a specific licence purpose.

**Comment by mjskay** [comment]
Response from my copyright folks (emphasis mine):

> Faculty members hold copyright in their scholarly works per SPG 601.28. "Scholarly work" is defined broadly: "SCHOLARLY WORKS means works authored by FACULTY within the scope of their employment as part of or in connection with their teaching, research, or scholarship. Common examples of SCHOLARLY WORKS include: lecture notes, case examples, course materials, textbooks, works of nonfiction, novels, lyrics, musical compositions/arrangements and recordings, journal articles, scholarly papers, poems, architectural drawings, **software**, visual works of art, sculpture, and other artistic creations, among others, regardless of the medium in which those works are fixed or disseminated."
> 
>You do not have to include the regents in your copyright notice on a scholarly work you created.

So you don't need to add Michigan to the copyright.

**Comment by jgabry** [comment]
Ok cool thanks!
