### ISSUE TITLE
Example dataset with a matrix and >1 chains

### ISSUE THREAD

**Issue by mjskay** [jgabry/posterior#31]
Following on #18, it might be helpful to have an example dataset with a 2-or-more dimensional variable (maybe a covariance matrix) and 2 or more chains for the purposes of examples and testing. Anyone have a good (and small) example like that on hand?

**Comment by paul-buerkner** [comment]
I have added the `multi_normal` example based on simulated data. It contains the mean vector (of length 3) and the covariance matrix (over dimension 3 x 3). This should be sufficient for testing and example purposes I think.
