### ISSUE TITLE
Bind multiple draws objects

### ISSUE THREAD

**Issue by paul-buerkner** [jgabry/posterior#45]
Kind of the inverse operation to subset, we should allow to find draws objects together. This involves (at least) two different kinds of bind operations.

- [x] bind variables together, that is, extend the variables dimension after maing sure the draws objects have the same number of draws (and iterations and chains). If draws are in the `draws_df` format this basically corresponds to a `cbind` operation.
- [x] bind draws together, that is extend the draws (or chains and iterations) dimension.  If draws are in the `draws_df` format this basically corresponds to a `rbind` operation.

I am not sure yet about good names for these two functions. Some ad-hoc ones could be `bind_*` where `*` could be one of variables, chains, iterations, or draws. What do you think?

**Comment by jgabry** [comment]
Yeah this would be useful. Will have a think about the names.

**Comment by paul-buerkner** [comment]
The `bind_draws` method is now implemented. Here are some examples:

```R
draws1 <- as_draws_list(example_draws())
draws2 <- subset_draws(draws1, chain = 2)
draws3 <- as_draws_df(data.frame(nu = rnorm(100)))

# bind along the chain dimension
bind_draws(draws1, draws2, along = "chain")

# bind along the variable dimension
bind_draws(draws2, draws3, along = "variable")
```

I wonder if `along` is the correct term though. Basically if `along = name` in binds along the `name` dimension. Does that make sense or is another term more descriptive? I am happy to hear your thoughts on this!

**Comment by paul-buerkner** [comment]
A follow up on this  @jgabry and @mjskay: Do you think the word `along` is the right one in that context?

**Comment by paul-buerkner** [comment]
I did not receive any complains so far so I will close this issue to clean up the issue tracker.
