### ISSUE TITLE
Use `subset_draws()` with alias `subset()` for consistency 

### ISSUE THREAD

**Issue by jgabry** [jgabry/posterior#48]
Because we already have the traditional `summary` as an alias for `summarise_draws`, I propose using `subset_draws` with `subset` as an alias. (This is also consistent with names like `repair_draws`, `order_draws`, `example_draws`, etc.).

**Comment by paul-buerkner** [comment]
Fine by me.

**Comment by jgabry** [comment]
Related to discussion of `thin()` in #5

**Comment by paul-buerkner** [comment]
Since we are about to make an alias anyway, we could also think of calling it `filter_draws` instead of `subset_draws`. I would try to avoid using both but I wanted to bring it up.

**Comment by jgabry** [comment]
I like filter but isn’t that usually used specifically for logical subsetting?

```r
subset_draws(x, iteration = 1:10)
filter_draws(x, iteration %in% 1:10)
```

Or am I mistaken?

**Comment by paul-buerkner** [comment]
You are right. Let's use subset_draws.

Jonah Gabry <notifications@github.com> schrieb am Do., 14. Nov. 2019, 20:40:

**Comment by paul-buerkner** [comment]
Should now be implemented.

**Comment by jgabry** [comment]
Thanks!
