### ISSUE TITLE
summarise_draws errors when called from another package

### ISSUE THREAD

**Issue by jgabry** [jgabry/posterior#49]
I noticed this when trying to incorporate posterior into cmdstanr, but here's an example that doesn't require cmdstanr:

```r
# simulate calling posterior from another package
detach(package:posterior) # or just start a new session and don't load the package
f <- function(...) {
  draws <- posterior::example_draws()
  posterior::summarise_draws(draws, ...)
}
Error: value for ‘rhat’ not found
```

@paul-buerkner looking at the code here 

https://github.com/jgabry/posterior/blob/c9ec5096474a083664040099e3827360d03c9390/R/summarise_draws.R#L79-L84

maybe this is because the functions like `rhat` aren't being looked for in the posterior package namespace?

**Comment by paul-buerkner** [comment]
I partially fixed that already for some specific functions but I need to
make this more general. I will look at this tomorrow.

Jonah Gabry <notifications@github.com> schrieb am Di., 12. Nov. 2019, 22:01:

**Comment by jgabry** [comment]
Thanks!

**Comment by paul-buerkner** [comment]
should be fixed now.
