### ISSUE TITLE
version numbers for alpha and beta releases?

### ISSUE THREAD

**Issue by jgabry** [jgabry/posterior#50]
Now that the repo is public should we start using version numbers and tagging releases? For example, we could do something like `0.0.1` for the alpha release (incrementing the 1 if we make important changes before beta), `0.1.0` for the beta release (same comment about incrementing), and `1.0.0` for the first CRAN release. Thoughts?

**Comment by paul-buerkner** [comment]
Sounds good to me.

Jonah Gabry <notifications@github.com> schrieb am Mi., 13. Nov. 2019, 18:44:

**Comment by jgabry** [comment]
Ok I'll bump the version to 0.0.1 and tag an alpha release!

**Comment by paul-buerkner** [comment]
Since we have basically decided on that matter, I will close this issue to keep the issue tracker clean.
