### ISSUE TITLE
Convert a draws_list to a draws_df

### ISSUE THREAD

**Issue by MansMeg** [jgabry/posterior#51]
```
> class(x)
[1] "pdb_gold_standard_draws" "draws_list"              "draws"                  
[4] "list"                   
> posterior::as_draws_df(x)
Error in class(out) <- class_draws_df() : 
  attempt to set an attribute on NULL
>   xdf <- posterior::as_draws_matrix(x)
Error in class(out) <- class_draws_df() : 
  attempt to set an attribute on NULL
> packageVersion("posterior")
[1] ‘0.0.1’
```

**Comment by paul-buerkner** [comment]
Thanks! Should be fixed now.

**Comment by jgabry** [comment]
Thanks for fixing. I think it would be good to add a test when fixing things like this so we make sure it still works as we continue to change the functions in the package.

**Comment by paul-buerkner** [comment]
I thought of that initially and somehow forgot when committing. I will do
it tomorrow.

Jonah Gabry <notifications@github.com> schrieb am Fr., 15. Nov. 2019, 19:43:
