### ISSUE TITLE
ESS and Rhat with NA in draws

### ISSUE THREAD

**Issue by avehtari** [jgabry/posterior#53]
See stan-dev/rstan#706

**Comment by paul-buerkner** [comment]
@yao-yl proposed the expected output to be 0 (for ESS) and Inf (for Rhat) as soon as some NAs appears in the input. I toally understand the reasons behind this expected output but wouldn't it be more consistent to simply return NA in accordance with standard R practices?

**Comment by MansMeg** [comment]
I agree. Also, maybe have a ’na.rm’ argument that defalts to FALSE?

**Comment by paul-buerkner** [comment]
Not sure about whether we should have an `na.rm` in the end. Let's discuss that later on at the meeting today if we have a few minutes for that.
