### ISSUE TITLE
Add resample_draws

### ISSUE THREAD

**Issue by avehtari** [jgabry/posterior#54]
Add resample_draws function similar to thin_draws. In thin_draws there is 
```
sel_iterations <- seq(1, niterations, by = thin)
subset(x, iteration = sel_iterations)
```
resample_draws would get optional weight vector and resampling algorithm name, and `sel_iterations` would be determined by the resampling algorithm, e.g.
 - simple resampling without replacement
 - simple resampling with replacement
 - deterministic resampling
 - stratified resampling

Stratified resampling is currently used in rstan and rstanarm when importance sampling is used to improve advi or optimizing.

The reference for different resampling algorithms:
Kitagawa, G., Monte Carlo Filter and Smoother for Non-Gaussian Nonlinear State Space Models, Journal of Computational and Graphical Statistics, 5(1):1-25, 1996.

**Comment by paul-buerkner** [comment]
Good idea! The only technical problem we will need to solve is that `subset` (or `subset_draws`) can only handle true subsetting so far, that is, they cannot select the same iteration twice as would be required for some resampling methods. We may need to add this possibility to `subset_draws` so that elements can be selected multiple times, at least when explicitely allowed by setting a flag accordingly. Or would it be better to add another method for this purpose?

**Comment by MansMeg** [comment]
I could probably help out with this if you would need some help @paul-buerkner .

**Comment by paul-buerkner** [comment]
Sure! Thank you! Let's discuss this on monday.

Måns Magnusson <notifications@github.com> schrieb am So., 8. Dez. 2019,
13:41:

**Comment by avehtari** [comment]
Stratified resampling can be copied from rstan/rstanarm, and I can provide reference code and some documentation text for different resampling methods.

**Comment by MansMeg** [comment]
Excellent! Can you give a pointer to the rstanarm code? It would be great to have it here in the issue.

**Comment by avehtari** [comment]
`.sanple_indices` https://github.com/stan-dev/rstanarm/blob/master/R/stan_glm.fit.R#L1058
and how it is used https://github.com/stan-dev/rstanarm/blob/master/R/stan_glm.fit.R#L631

**Comment by MansMeg** [comment]
Thanks!

**Comment by paul-buerkner** [comment]
Non-unqiue subsetting is now possible by setting `unique = FALSE` in `subset_draws`. For example

```R
x <- example_draws()
# extract the first chain twice
subset_draws(x, chain = c(1, 1), unique = FALSE)
```

This feature should make implementing `resample_draws` possible @MansMeg

**Comment by paul-buerkner** [comment]
@MansMeg I am assigning you to this issue, as to my understanding you wanted to work on it anyway. Please tell me if you need any help.

**Comment by paul-buerkner** [comment]
I have added a `resample_draws` prototype in the **resample_draws** branch to provide the basis for our discussion in the next few days.

**Comment by paul-buerkner** [comment]
supported via PR #65
