### ISSUE TITLE
Add to readme an example "Converting from draws formats to regular R objects"

### ISSUE THREAD

**Issue by avehtari** [jgabry/posterior#56]
readme has now a useful example "Converting from regular R objects to draws formats". It would be also useful to have an example "Converting from draws formats to regular R objects" (as I'm still not very experienced with R, it took me some time to figure out how can I get just the numeric values for one parameter in a format accepted by regular R functions).

**Comment by paul-buerkner** [comment]
We could clarify that our draws objects are in fact just matrices/arrays/data.frames/lists which can be treated as any other objects of that class.

**Comment by avehtari** [comment]
Show an explicit example for replacing `extract(..., permuted=FALSE)` in RStan,

It is probably obvious for you how to further switch between objects, but even after a few years of R use, I'm still frustrated when I can see the numbers with print or summary, but when I provide the object to some function I get just an error which doesn't tell to which type I should cast my object. 
For example this gives an error (also with as_draws_array)
```
qplot(subset(as_draws_df(fitp2b), variable="sigma")[,'sigma'])
```
So the draws object is something qplot and many base functions don't recognize and additional
casting is required
```
qplot(as.matrix(subset(as_draws_df(fitp2b), variable="sigma")[,'sigma']))
```
Here qplot is just one example, I had the same problem with some base functions. The above subset to matrix solution is also annoying as it requires `sigma` twice.

**Comment by paul-buerkner** [comment]
I have improve the documentation in that regard. Your problem with `qplot` was unrelated to posterior but related to the fact that qplot only accepts matrices not data.frames. That is, `draws_matrix` objects are naturally supported as well.

I don't understand what you mean by "replacing extract(..., permuted=FALSE) in Rstan"? Can you elaborate a little bit.

**Comment by avehtari** [comment]
`extract` by default permutes which is evil. That default behavior cannot be changed, so the discussion has been that `extract` should be deprecated and it would be useful to have simplest possible example how to replace extract and when people start with that they will eventually get seduced by the other benefits of posterior.

**Comment by paul-buerkner** [comment]
Ok, I get what you mean and I agree `extract` should be deprecated. Once posterior is on CRAN, we can merge a PR into rstan that enables to use of `as_draws_array(...)` to replace `extract(..., permuted=FALSE)` as both will have almost the same output (with the exception of dimnames). 

Along similar lines, we can change the internals of `as.array`, `as.data.frame` etc. of rstan to use the posterior package under the hood.
