### ISSUE TITLE
summarise_draws should accept functions for `measures =`

### ISSUE THREAD

**Issue by mjskay** [jgabry/posterior#58]
It occurs to me that the form of #57 suggested by @paul-buerkner (`mcse_fun(...)`) will be easier to use if summarise_draws accepts functions for the `measures` argument, which it probably should do anyway (currently it only accepts strings). We could use `rlang::as_function`, in which case `~` functions would also work, allowing syntax like this: 

```r
summarise_draws(x, measures = c(mean, ~ mcse_fun(., mean))
```

Or if we don't use as_function you could still use magrittr-style lambdas with the pipe:

```r
summarise_draws(x, measures = c(mean, . %>% mcse_fun(mean))
```

**Comment by paul-buerkner** [comment]
This is true. And it also avoids potential namespace clashes if the function named via string appears in multiple namespaces.

**Comment by tjmahr** [comment]
Quick note, `as_function()` supports:

- named functions `mean`
- formula style functions `~ .x - mean(.x)`
- pipeline style functions `. %>% mean() %>% round(2)`
- strings `"mean"`

(I don't want to give the impression that `as_function()` only works with formula style functions.)

**Comment by paul-buerkner** [comment]
I think with this we are moving closer to what `dplyr::summarise` does just that we do not pass the variables explicitely to the functions but. If we get rid of `measures` and instead use `...` for this purpose, we can easily pass column names via argument names. Alternatively, if we decide to stick with `measures`,  we could pass column names as names of list/vector elements.

**Comment by paul-buerkner** [comment]
I have changed the internals of `summarise_draws` to offer much greater flexibility. Here are some examples:

```R
x <- example_draws("eight_schools")

summarise_draws(x)
summarise_draws(x, "mean", "median")
summarise_draws(x, default_convergence_measures())
summarise_draws(x, mean, mcse = mcse_mean)
summarise_draws(x, ~quantile(.x, probs = c(0.4, 0.6)))

library(magrittr)
summarise_draws(x, mean = . %>% mean() %>% round(1))
```

**Comment by paul-buerkner** [comment]
Is there anything we should support that is not supported after the recent changes?

**Comment by paul-buerkner** [comment]
I think all relevant ways of specifying measures are now working so I will close this issue.
