### ISSUE TITLE
What to do with the 'extract_one_variable_matrix' method?

### ISSUE THREAD

**Issue by paul-buerkner** [jgabry/posterior#60]
We currently use `extract_one_variable_matrix` as the method to extract a matrix of iterations and chains for a single variable. With the latest change I made, it is no longer used in `summarize_draws` because it creates a lot of run time overhead that we can avoid when we know we will loop over all variables (thanks @avehtari for making me aware of the speed issues).

My two questions are now:

1. Shall we keep this method in the package at all?
2. If we decide "yes" on (1), can we find a better name that is somewhat less verbose?

**Comment by jgabry** [comment]
Hmm, do you think there's a use case for it if it's not needed for summarize_draws? I'm ok with keeping it if we think it will be used. For name, we could shorten it a little by dropping "one", so `extract_variable_matrix()`. Is that short enough?

**Comment by paul-buerkner** [comment]
Yeah, `extract_variable_matrix()` shounds reasonable to me. The potential use case could be if users decide to compute specifc convergence diagnostics manually for particular parameters. Clearly, this is also addressed via `summarize_draws` so I don't know how helpful it actually is.

**Comment by jgabry** [comment]
@paul-buerkner Actually I realized that we're using `posterior::extract_one_variable_matrix()` in CmdStanR in our code to check divergences and treedepth. It's fine to rename it but definitely let me know first so we can switch to the new name in CmdStanR without breaking anything.

**Comment by paul-buerkner** [comment]
I am happy with `extract_variable_matrix` or with similar names. Feel free to change it yourself, if you like, so that you also control the timing. Otherwise, I think I will have the time end of next week and tell you before I will push the change.

**Comment by paul-buerkner** [comment]
I would like to rename to `extract_variable_matrix` today or tomorrow. @jgabry  can you confirm this is ok with you?
