### ISSUE TITLE
Converting from older formats

### ISSUE THREAD

**Issue by mtwest2718** [jgabry/posterior#62]
Resurrecting the question addressed in #16 as I am new and think its more feasible if we write only one way transforms (to _Posterior_). Investigating the _coda_ [archive](https://cran.r-project.org/src/contrib/Archive/coda/) and [changelog](https://cran.r-project.org/web/packages/coda/ChangeLog), very little of the code has changed in the past five years. Also the functions that handle `mcmc` objects as well as BUGS & JAGS files do not require external libraries.

I would argue that the value of an expanded user base for this library and its downstream tools outweighs the code maintenance cost.

**Comment by paul-buerkner** [comment]
I didn't add a comment on why I closed #16 but if I remember it correctly, it was because working with them would have required importing coda which we want to avoid. If we can find a way to support them in some way without importing coda, I agree we should consider it.

**Comment by mtwest2718** [comment]
Summary of afternoon conversation with @paul-buerkner
- Proposal: Asymmetric transformation of `mcmc` and `mcmc.list` objects to draws objects and **not** vice versa.
- _Coda_'s library is stable enough that we need not worry about the structure of `mcmc` object types changing. The object ingestion and transformation in `coda` itself is all done with base `R`, so it would be possible to port these functions without needing to reference any other package.
- Determine if there are any posterior summary diagnostic methods of `mcmc` objects that are worth porting over that aren't already in _posterior_.
    - gweke, gelman, heidel, raftery
    - cross-correlation
- I (@mtwest2718) would like to take this on as my first code task here, in part to get familiar with the _posterior_ package.

**Comment by jgabry** [comment]
Sounds good, thanks @mtwest2718!

**Comment by mtwest2718** [comment]
Playing around with the output this **rJAGS** example, the conversion from `mcmc` object to any of the draws formats works as is without any changes. This may be due to small blocks found in each of the _as_draws*_ R files like the below (_as_draws_list.R_ lines 64-68).

    #' @rdname draws_list
    #' @export
    as_draws_list.mcmc <- function(x, ...) {
      as_draws_list(as_draws_matrix(x), ...)
    }
The `mcmc.list` method is also in the code base

    #' @rdname draws_list
    #' @export
    as_draws_list.mcmc.list <- function(x, ...) {
      as_draws_list(as_draws_array(x), ...)
    }
and looks to be working alright. Running `git log as_draws_df.R`, the only possible pointer is commit _52c06dcac0759c2d12193fa708676f2806193027_ regarding issue #16 by @paul-buerkner from last November. While the issue was closed seemingly in the negative, the draft code was never removed from the repo. I would like to do some more testing just to make sure results structurally match what they should look like if we were transforming **rstanarm** samples.

There may be a development process issue here if there is functionality lurking in the codebase that our resolutions suggest shouldn't exist, but I'd like to take that to Slack or email.

**Comment by paul-buerkner** [comment]
Nice! I totally forgot about that but apparently we did resolve the issue
by implementing these functions so that's great!

WestByNoreaster <notifications@github.com> schrieb am Mo., 2. März 2020,
13:55:

**Comment by paul-buerkner** [comment]
It as I see the code I now remember that it was likely me implementing
these functions so at least we know who to blame :-D

Paul Buerkner <paul.buerkner@gmail.com> schrieb am Mo., 2. März 2020, 15:57:

**Comment by mtwest2718** [comment]
>> git blame paul

Before I close this out, I want to test a few more packages that produce output using coda, just to make sure things work as desired/expected. Is there any place to put the testing script?

**Comment by paul-buerkner** [comment]
You could put it in a folder under tests/ and make sure to add it to
.Rbuildignore (I forgot the exact file name right now) so that it is not
included in the built R package.

WestByNoreaster <notifications@github.com> schrieb am Di., 3. März 2020,
15:23:

**Comment by paul-buerkner** [comment]
Is there anything that needs to be done before we can close this issue?

**Comment by mtwest2718** [comment]
No we are good.
