### ISSUE TITLE
Drop 'tibble' dependency?

### ISSUE THREAD

**Issue by paul-buerkner** [jgabry/posterior#64]
`draws_df` now has its own print method independently of tibble, which is not as pretty at the tibble version (yet), but more tuned to the specific use case. We could make a similar kind of print method for `draws_summary` objects (returned by `summarise_draws`). The increased consistency of tibbles, that is, no dropping of dimensions and no partial matching could be manually enforced by us as well without relying on tibble. 

So my question is if we need the tibble dependency at all? To be clear, I am not againt this dependency, I just wanted to bring it up and discuss before we cannot change it anymore.

**Comment by mjskay** [comment]
I don't have a strong preference. FWIW, the rvar stuff currently does not need {tibble}, but does depend on {pillar}, which is the formatting/printing package {tibble} uses to pretty-print custom data types when they are put into a column in a tibble. 

I do wonder about the trade-offs in duplicating (and maintaining) functionality provided by tibble. Given the large set of packages depending on tibble (directly or indirectly) it strikes me as a dependency likely to exist on most machines. Do we need formatting so different from tibbles that it is worth moving the maintenance burden into posterior?

**Comment by paul-buerkner** [comment]
You have good points. The price for having the tibble dependency is probably so small that the benefits, if even not too large, are still worth it.
