### ISSUE TITLE
Comparing chains from different MCMC runs

### ISSUE THREAD

**Issue by bbbales2** [jgabry/posterior#67]
Is there any easy way if I have a posterior::as_draws_matrix or something from one fit and then a posterior::as_draws_matrix from another than I can combine these and check the statistics of the combined object?

I'm trying to easily when I've written a model using parallelization I did it properly.

**Comment by bbbales2** [comment]
In particular, for cmdstanr if I have a ```fit$draws()``` object. Right now I build a new array and pack it with the contents of two ```fit$draws()``` objects but that loses the naming and such.

**Comment by paul-buerkner** [comment]
Does bind_draws do the trick?

Ben Bales <notifications@github.com> schrieb am Fr., 17. Apr. 2020, 18:38:

**Comment by bbbales2** [comment]
It does it does! Thank you!
