### ISSUE TITLE
bind_draws with one argument NULL

### ISSUE THREAD

**Issue by rok-cesnovar** [jgabry/posterior#68]
Would it be possible to allow `bind_draws(a, b, along = "chain")`, where a = NULL.

It currently errors out. Or is this intentional?

Thanks.

**Comment by paul-buerkner** [comment]
It is how R does method dispatch only on the first argument. I will write a
default method to handle some other cases such as the one you mentioned.

Rok Češnovar <notifications@github.com> schrieb am Mi., 13. Mai 2020, 22:50:

**Comment by rok-cesnovar** [comment]
Ah yeah, makes sens. Thanks for the quick reply!

**Comment by paul-buerkner** [comment]
NULL elements should now be removed in `bind_draws` but at least one valid draws object needs to be passed for the method to work.
