### ISSUE TITLE
Document edge case behavior for summary functions (e.g. rhat and ess)

### ISSUE THREAD

**Issue by avehtari** [jgabry/posterior#70]
Related to the discussion of warnings of Rhat and ESS being NA at Stan discourse https://discourse.mc-stan.org/t/largest-rhat-is-na-when-one-parameter-is-fixed-to-a-constant/15488/5
and the older discussion of behavior for constant draws
https://discourse.mc-stan.org/t/ess-rhat-behavior-for-chains-numerical-consistent-with-constants/10465

tl;dr for the above: When all draws for a parameter have the same value, we can't know whether it is due to 1) the parameter being fixed, 2) limited floating point accuracy, 3) for a discrete quantity one state has high probability and the chain is not visiting the other states, 4) chains are stuck. Due to the ambiguity rhat and ess functions return NA. This is not yet documented in function help texts.

Add to function documentations (such as ess_basic, ess_bulk, ess_quantile,  ess_sd,  ess_tail, mcse_mean, mcse_quantile, mcse_sd, rhat, rhat_basic) what is the output in different edge cases
- all draws have the same value
- some draws have Inf, -Inf, NaN, or NA

**Comment by paul-buerkner** [comment]
Thanks! I will take care of this.

**Comment by paul-buerkner** [comment]
What is the right output if some input is `Inf`? Right now, `rhat` can handle this case due to rank normalization working with infinite values. Is this desirable or shall we also return NA if any input if `Inf` or `-Inf`?

**Comment by avehtari** [comment]
I would go with NA, and make helper functions for checking constant value, -Inf, Inf, NaN, NA in the draws and provide warnings if those are encountered. I would not by default give warnings everytime when rhat etc are computed, but make it easy to provide appropriate warnings for higher level diagnostic functions.

**Comment by paul-buerkner** [comment]
Ok. I will make the output NA then. How to propagate the warnings to higher-level functions without returning warnings for each rhat is another issue, that we should address in another issue.

**Comment by paul-buerkner** [comment]
The behavior should now be more consistent and the doc is updated accordingly. I am not sure about the warnings to be honest, but I think this discussion should go into another issue.

**Comment by MansMeg** [comment]
Sorry for be a party-pooper, but this would differ from the common behaviour in R. 

> mean(c(1, NA))
NA
> mean(c(1, Inf))
Inf
> mean(c(1, NaN))
NaN

(No one throws a warning)

I guess it is better to conform to this way of handling Edge cases if we dont have a good reason? Or what do you think? Although I dont think it is a big thing. Sorry for my late comment.

**Comment by paul-buerkner** [comment]
For `mean` this makes sense, but I don't think these conventions make sense for our diagnostics. There is nothing specific to learn about NA vs. NaN that has any meaning for most users. For example, `is.na` evaluates to TRUE fro both NA and NaN. Also, handling all of these special cases comes at the cost of having each post processing function dealing with this, separetely, because an NaN in a certain operations will become NA, and Inf will become NaN (e.g., in `Inf / Inf`). For our convergence diagnostics, there is not really any meaning conveyed by these different outputs in my opinion, so I prefer having a single one that simply says I couldn't obtain a sensible result (and have these cases documented).

**Comment by avehtari** [comment]
Diagnostics is different from mean. Here's an summarise_draws example with one constant
```
# A tibble: 3 x 10
  variable   mean median    sd   mad     q5    q95  rhat ess_bulk ess_tail
  <chr>     <dbl>  <dbl> <dbl> <dbl>  <dbl>  <dbl> <dbl>    <dbl>    <dbl>
1 theta     0.665  0.675 0.129 0.134  0.434  0.857  1.00    1486.    2307.
2 x         1      1     0     0      1      1     NA         NA       NA 
3 lp__     -8.13  -7.86  0.682 0.310 -9.51  -7.64   1.00    2131.    2328.
```
This is how I like it to be for a constant x. If there would be, e.g. one Inf draw for one of the parameters, then mean would Inf, median would be median, sd would be NaN, etc, and rhat and ess's would be NA.

When computing and showing this summary there is no need for warnings. I agree that warnings are separate issue, but wanted to mention the warnings here as I think that we don't need to separate in the output of rhat and ess's different reasons for NA, but instead, for example, when finishing the sampling we could provide warnings if there are NaNs, Infs, constants or other unusual things in the posterior draws.

**Comment by MansMeg** [comment]
Alright, I just wanted to raise the issue for awareness. In practice, I agree it would not matter much, as you say.
